name: Angular CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:ci

      - name: Test
        run: npm run test:ci
        
      - name: Run a multi-line script
        run: echo Everything went fine.
