name: Angular CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm install
        working-directory: fluentpos/src/client/
    
      - name: Build Application
        run: npm run build
        working-directory: fluentpos/src/client/
      
      - name: List Files in Distribution Directory
        run: ls -R ./dist
